language: c

dist: xenial

addons:
    apt:
        packages:
            - valac
            - libgee-0.8-dev
            - libpulse-dev
            - meson
            - ninja

script:
    - meson builddir
    - ninja -C builddir
    - ninja -C builddir test