language: c

dist: xenial

addons:
    apt:
        packages:
            - valac
            - libgee-0.8-dev
            - libpulse-dev
            - ninja-build
            - meson

script:
    - mkdir builddir
    - meson ./ ./builddir
    - ninja -C builddir
    - ninja -C builddir test