language: c

dist: xenial

addons:
    apt:
        sources:
            - sourceline: 'ppa:jonathonf/meson'
            - sourceline: 'ppa:jonathonf/gtk3.22'
            - sourceline: 'ppa:vala-team/ppa'
        packages:
            - valac
            - libgee-0.8-dev
            - libpulse-dev
            - libgtk-3-dev
            - ninja-build
            - meson

script:
    - mkdir builddir
    - meson ./ ./builddir
    - ninja -C builddir
    - ninja -C builddir test